uwsgi:
  http-timeout: "86400"
  http-timeout: "86400"
  buffer-size: "32768"
  buffer-size: "32768"
  log-format: "combined"
  log-date: true
  http-timeout: "86400"
  log-x-forwarded-for: true
  buffer-size: "32768"
  buffer-size: "32768"
  route-host: "^(?P<host>[^/]+)"
  buffer-size: "32768"
  route-uri: "^(?P<path>[^?]*)(?:\?(?P<args>.*))?$"
  buffer-size: "32768"
  offload-threads: 1
  buffer-size: "32768"
  route-label: "route"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
  buffer-size: "32768"
